networks:
  elk:

volumes:
  esdata:

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    volumes:
      - ./configs/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - ./logs/syslog-ng:/var/log/syslog-ng
      - ./logs/snort:/var/log/snort
    restart: unless-stopped
    networks:
      - elk

  snort:
    image: frapsoft/snort
    container_name: snort
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    volumes:
      - ./configs/snort:/etc/snort
      - ./logs/snort:/var/log/snort
    command: ["-c", "/etc/snort/snort.conf", "-i", "any"]
    restart: unless-stopped

  web:
    image: php:8.1-apache
    container_name: web
    volumes:
      - ./configs/web/:/var/www/html/:ro
      - ./logs/syslog-ng:/var/log/syslog-ng  # <-- on monte le même dossier que syslog-ng
    ports:
      - "8080:80"
    restart: unless-stopped
    command: >
      bash -c "apache2-foreground 2>&1 | tee -a /var/log/syslog-ng/apache.log"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    command: ["--strict.perms=false", "-e", "-d", "*"]
    container_name: filebeat
    user: root
    volumes:
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/syslog-ng/all.log:/var/log/syslog-ng/all.log:ro
    depends_on:
      - elasticsearch
      - syslog-ng
    networks:
      - elk
    restart: unless-stopped
