# ============================== Filebeat inputs ===============================
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/syslog-ng/all.log
    scan_frequency: 10s       # vérifie le fichier toutes les 10 secondes
    tail_files: true          # lit uniquement les nouvelles lignes à partir du démarrage
# ============================== Filebeat modules =============================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ============================== Output =======================================
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

# ============================== Setup ========================================
setup.kibana:
  host: "http://kibana:5601"

# ============================== Logging ======================================
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
